// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $edit from "./routes/edit.tsx";
import * as $index from "./routes/index.tsx";
import * as $upload from "./routes/upload.tsx";
import * as $watch from "./routes/watch.tsx";
import * as $EditVideo from "./islands/EditVideo.tsx";
import * as $UploadVideo from "./islands/UploadVideo.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/edit.tsx": $edit,
    "./routes/index.tsx": $index,
    "./routes/upload.tsx": $upload,
    "./routes/watch.tsx": $watch,
  },
  islands: {
    "./islands/EditVideo.tsx": $EditVideo,
    "./islands/UploadVideo.tsx": $UploadVideo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
