name: Deploy
on:
  push:
    branches: prod
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    env:
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      PORT: ${{ secrets.PORT }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
      S3_PORT: ${{ secrets.S3_PORT }}
      S3_USE_SSL: ${{ secrets.S3_USE_SSL }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_REGION: ${{ secrets.S3_REGION }}  
      
    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Copy files
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
        
      - name: Restart server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl --user restart ${{ secrets.SERVICE_NAME }}.service && exit"
          
